version: "3.0"
services:
  blog_app:
    build:
      context: .
    container_name: blog-app
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html/
    networks:
      - app
    depends_on:
      - blog_db

  blog_nginx:
    image: nginx:1.26.1
    container_name: blog-nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8001:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www/html/
    networks:
      - app
    depends_on:
      - blog_app

  blog_db:
    image: mysql:8.0
    container_name: blog-db
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    volumes:
      - ./data/blog_db.sql:/docker-entrypoint-initdb.d/data.sql
      - blog_db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456789
    networks:
      - app
    expose:
      - 3306

volumes:
  blog_db_data:
    driver: local

networks:
  app:
    driver: bridge